name: Java CI with Maven

on:
  push:
    branches: [ "original" ]
  pull_request:
    branches: [ "original" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - run: mkdir client/target/libs
    - run: mv client/target/runescape-1.0.jar client/target/libs/rt4-client.jar
    - run: sha256sum client/target/libs/rt4-client.jar | cut -d ' ' -f 1 | tr -d '\n' > client/target/libs/rt4-client.jar.sha256

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: rt4-client
        path: client/target/libs/*
